### ISSUE TITLE
Great job ! New development ?

### ISSUE THREAD

**Issue by ddotta** [ablack3/shinyPivot#2]
Hi !  
Great module, but I wonder why you stopped developing it?  
Did you maybe continue your work on another project?

**Comment by ablack3** [comment]
Thanks! No I have not really done much more with this in a while. I was using it as part of an internal shiny application. I don't quite feel like a professional R developer yet but am trying to get there. If there is interest in turning this into a package I could certainly do that. I think the difficulty is that each use case is going to be different. It is tough to make it generic enough but still useful for each specific use case in an application. In just one shiny app I ended up with three different versions of the module. Definitely open to suggestions! Thanks for the feedback!
